services:
  angular:
    build: ./my-angular-app
    environment:
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - API_URL=${API_URL}
      - WS_URL=${WS_URL}
    ports:
      - "443:443"
      - "80:80"
    networks:
      - my-app-network
  server:
    build: ./my-app-server
    environment:
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - API_URL=${API_URL}
      - WS_URL=${WS_URL}
    ports:
      - "5000:5000"
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge