name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22
          
      - name: Create certs directory
        run: |
          mkdir -p my-angular-app/certs

          - name: Write cert.pem
            run: |
              echo "${{ secrets.CERT_PEM }}" > my-angular-app/certs/cert.pem

          - name: Write key.pem
            run: |
              echo "${{ secrets.KEY_PEM }}" > my-angular-app/certs/key.pem

      - name: Install dependencies (Frontend)
        run: |
          cd my-angular-app
          npm install
          
      - name: Make replace-env.sh executable
        run: |
          cd my-angular-app
          chmod +x replace-env.sh

      - name: Replace placeholders in environment.prod.ts
        run: |
          cd my-angular-app
          ./replace-env.sh
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          API_URL: ${{ secrets.API_URL }}
          WS_URL: ${{ secrets.WS_URL }}

      - name: Build Angular app
        run: |
          cd my-angular-app
          npm run build-prod

      - name: Install dependencies (Backend)
        run: |
          cd my-app-server
          npm install
          
      - name: Create certs directory
        run: |
          mkdir -p my-app-server/certs

      - name: Write cert.pem
        run: |
          echo "${{ secrets.CERT_PEM }}" > my-app-server/certs/cert.pem

      - name: Write key.pem
        run: |
          echo "${{ secrets.KEY_PEM }}" > my-app-server/certs/key.pem

      - name: Build and deploy Docker containers
        run: |
          docker-compose up --build -d
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          API_URL: ${{ secrets.API_URL }}
          WS_URL: ${{ secrets.WS_URL }}